=== UHH2/JetMass/config/VqqJetsJobConfig.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- ======================================================================= -->
<!-- @Project: SFrame - ROOT-based analysis framework for ATLAS              -->
<!-- @Package: User                                                          -->
<!--                                                                         -->
<!-- @author Stefan Ask       <Stefan.Ask@cern.ch>           - Manchester    -->
<!-- @author David Berge      <David.Berge@cern.ch>          - CERN          -->
<!-- @author Johannes Haller  <Johannes.Haller@cern.ch>      - Hamburg       -->
<!-- @author A. Krasznahorkay <Attila.Krasznahorkay@cern.ch> - CERN/Debrecen -->
<!--                                                                         -->
<!-- This is the dtd that can be used to configure an SFrame job             -->
<!--                                                                         -->
<!-- ======================================================================= -->

<!ELEMENT JobConfiguration ((PyLibrary|Library|Package)*,Cycle+) >
<!ATTLIST JobConfiguration
        JobName              CDATA            #REQUIRED
        OutputLevel          CDATA            "INFO"
>

<!ELEMENT PyLibrary EMPTY>
<!ATTLIST PyLibrary
        Name                 CDATA            #REQUIRED
>

<!ELEMENT Library EMPTY>
<!ATTLIST Library
        Name                 CDATA            #REQUIRED
>

<!ELEMENT Package EMPTY>
<!ATTLIST Package
        Name                 CDATA            #REQUIRED
>

<!ELEMENT Cycle (InputData+,UserConfig?)>
<!ATTLIST Cycle
        Name                 CDATA            #REQUIRED
        TargetLumi           CDATA            #REQUIRED
        OutputDirectory      CDATA            "./"
        PostFix              CDATA            ""
        RunMode              (LOCAL|PROOF)    "LOCAL"
        ProofServer          CDATA            ""
        ProofWorkDir         CDATA            ""
        ProofNodes           CDATA            "-1"
        UseTreeCache         (True|False|1|0) "False"
        TreeCacheSize        CDATA            "30000000"
        TreeCacheLearnEntries CDATA           "100"
        ProcessOnlyLocal     (True|False|1|0) "False"
        GridFile             CDATA            "JetMass/Histograms/grid.root"
>

<!ELEMENT InputData ((GeneratorCut|DataSet|In|InputTree|OutputTree|
                      MetadataInputTree|MetadataOutputTree)*) >
<!ATTLIST InputData
        Type                 CDATA            #REQUIRED
        Version              CDATA            #REQUIRED
        Lumi                 CDATA            "0.0"
        NEventsMax           CDATA            "-1"
        NEventsSkip          CDATA            "0"
        Cacheable            (True|False)     "False"
        SkipValid            (True|False)     "False"
>

<!ELEMENT GeneratorCut EMPTY>
<!ATTLIST GeneratorCut
        Tree                 CDATA            #REQUIRED
        Formula              CDATA            #REQUIRED
>

<!ELEMENT DataSet EMPTY>
<!ATTLIST DataSet
        Name                  CDATA            #REQUIRED
        Lumi                  CDATA            #REQUIRED
>

<!ELEMENT In EMPTY>
<!ATTLIST In
        FileName              CDATA            #REQUIRED
        Lumi                  CDATA            #REQUIRED
>

<!ELEMENT OutputTree EMPTY>
<!ATTLIST OutputTree
        Name                  CDATA            #REQUIRED
>

<!ELEMENT InputTree EMPTY>
<!ATTLIST InputTree
        Name                  CDATA            #REQUIRED
>

<!ELEMENT MetadataInputTree EMPTY>
<!ATTLIST MetadataInputTree
        Name                  CDATA            #REQUIRED
>

<!ELEMENT MetadataOutputTree EMPTY>
<!ATTLIST MetadataOutputTree
        Name                  CDATA            #REQUIRED
>

<!ELEMENT UserConfig (Item*)>

<!ELEMENT Item EMPTY>
<!ATTLIST Item
        Name                  CDATA            #REQUIRED
        Value                 CDATA            #REQUIRED
>
        
<!ENTITY DATA_JetHTRun2017B  SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/DATA_JetHT_2017B.xml">
<!ENTITY DATA_JetHTRun2017C  SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/DATA_JetHT_2017C.xml">
<!ENTITY DATA_JetHTRun2017D  SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/DATA_JetHT_2017D.xml">
<!ENTITY DATA_JetHTRun2017E  SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/DATA_JetHT_2017E.xml">
<!ENTITY DATA_JetHTRun2017F  SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/DATA_JetHT_2017F.xml">

<!ENTITY QCD_Pt_170to300 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_170to300_TuneCP5_13TeV_pythia8_Fall17_v1.xml">
<!ENTITY QCD_Pt_170to300_ext1 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_170to300_TuneCP5_13TeV_pythia8_Fall17_ext1_v2.xml">
<!ENTITY QCD_Pt_300to470 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_300to470_TuneCP5_13TeV_pythia8_Fall17_v1.xml">
<!ENTITY QCD_Pt_300to470_ext1 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_300to470_TuneCP5_13TeV_pythia8_Fall17_ext1.xml">
<!ENTITY QCD_Pt_470to600 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_470to600_TuneCP5_13TeV_pythia8_Fall17_v1.xml">
<!ENTITY QCD_Pt_470to600_ext1 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_470to600_TuneCP5_13TeV_pythia8_Fall17_ext1.xml">
<!ENTITY QCD_Pt_600to800 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_600to800_TuneCP5_13TeV_pythia8_Fall17_v1.xml">
<!ENTITY QCD_Pt_600to800_ext1 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_600to800_TuneCP5_13TeV_pythia8_Fall17_ext1_v2.xml">
<!ENTITY QCD_Pt_800to1000 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_800to1000_TuneCP5_13TeV_pythia8_Fall17_v1.xml">
<!ENTITY QCD_Pt_800to1000_ext1 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_800to1000_TuneCP5_13TeV_pythia8_Fall17_ext1_v2.xml">
<!ENTITY QCD_Pt_1000to1400 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_Fall17_v1.xml">
<!ENTITY QCD_Pt_1000to1400_ext1 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_Fall17_ext1_v2.xml">
<!ENTITY QCD_Pt_1400to1800 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8_Fall17_v1.xml">
<!ENTITY QCD_Pt_1400to1800_ext1 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8_Fall17_ext1.xml">
<!ENTITY QCD_Pt_1800to2400 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_1800to2400_TuneCP5_13TeV_pythia8_Fall17_v1.xml">
<!ENTITY QCD_Pt_2400to3200 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_2400to3200_TuneCP5_13TeV_pythia8_Fall17_v1.xml">
<!ENTITY QCD_Pt_3200toInf SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_3200toInf_TuneCP5_13TeV_pythia8_Fall17_v1.xml">
<!ENTITY QCD_Pt_3200toInf_ext1 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/QCD/QCD_Pt_3200toInf_TuneCP5_13TeV_pythia8_Fall17_ext1_v1.xml">

<!ENTITY WJetsToQQ_HT400to600 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/MC_WJetsToQQ_HT400to600_qc19_3j_TuneCP5_13TeV-madgraphMLM-pythia8.xml">
<!ENTITY WJetsToQQ_HT600to800 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/MC_WJetsToQQ_HT600to800_qc19_3j_TuneCP5_13TeV-madgraphMLM-pythia8.xml">
<!ENTITY WJetsToQQ_HT800toInf SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/MC_WJetsToQQ_HT800toInf_qc19_3j_TuneCP5_13TeV-madgraphMLM-pythia8.xml">

<!ENTITY ZJetsToQQ_HT400to600 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/MC_ZJetsToQQ_HT400to600_qc19_4j_TuneCP5_13TeV-madgraphMLM-pythia8.xml">
<!ENTITY ZJetsToQQ_HT600to800 SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/MC_ZJetsToQQ_HT600to800_qc19_4j_TuneCP5_13TeV-madgraphMLM-pythia8.xml">
<!ENTITY ZJetsToQQ_HT800toInf SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v2/2017/MC_ZJetsToQQ_HT800toInf_qc19_4j_TuneCP5_13TeV-madgraphMLM-pythia8.xml">

<!ENTITY TTToHadronic SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v1/2017/MC_TTToHadronic_TuneCP5_13TeV-powheg-pythia8.xml">
<!ENTITY TTToSemiLeptonic SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v1/2017/MC_TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8.xml">

<!ENTITY ST_tW_top SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v1/2017/ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.xml">
<!ENTITY ST_tW_antitop SYSTEM "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/common/UHH2-datasets/RunII_102X_v1/2017/ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.xml">

=== UHH2/JetMass/config/Vqq_jets_PreSel_scaleStudy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JobConfiguration PUBLIC "" "/afs/desy.de/user/a/albrechs/xxl/af-cms/UHH2/10_2/CMSSW_10_2_10/src/UHH2/JetMass/config/VqqJetsJobConfig.dtd" [
<!ENTITY NEVT "-1">
<!ENTITY OUTdir   "/nfs/dust/cms/user/albrechs/UHH2/JetMassOutput/WJetsTrees/scaleStudy/">
<!ENTITY SAMPLES SYSTEM "Vqq_jets_samples.xml">
]>

<!--
<ConfigParse NEventsBreak="0" LastBreak="0" FileSplit="40"/>
<ConfigSGE RAM="4" DISK="4" Mail="steffen.albrecht@desy.de" Notification="as" Workdir="workdir_Vqq_scaleStudy"/>
-->

<JobConfiguration JobName="VqqJetsScaleStudyJob" OutputLevel="INFO">
  <Library Name="libSUHH2JetMass"/>
  <Package Name="SUHH2JetMass.par"/>

  <Cycle Name="uhh2::AnalysisModuleRunner" OutputDirectory="&OUTdir;/oneScale/" PostFix="" TargetLumi="41860">
    &SAMPLES;
    <UserConfig>
      <Item Name="GridFile" Value="JetMass/Histograms/grid_oneScale.root" />
      <Item Name="channel" Value="W"/>
      <Item Name="PrimaryVertexCollection" Value="offlineSlimmedPrimaryVertices"/>
      <Item Name="GenParticleCollection"   Value="GenParticles"/>
      <Item Name="ElectronCollection"      Value="slimmedElectronsUSER"/>
      <Item Name="MuonCollection"          Value="slimmedMuonsUSER"/>
      <Item Name="JetCollection"           Value="jetsAk4CHS"/>
      <Item Name="GenJetCollection"        Value="slimmedGenJets"/>
      <Item Name="TopJetCollection"        Value="jetsAk8PuppiSubstructure_SoftDropPuppi"/>
      <Item Name="GenTopJetCollection"     Value="genjetsAk8SubstructureSoftDrop" />
      <Item Name="PFParticleCollection"    Value="PFParticles"/>
      <Item Name="METName"                 Value="slimmedMETs"/>
      <Item Name="use_sframe_weight" Value="false"/>
      <Item Name="dometfilters" Value="true" />
      <Item Name="dopvfilter" Value="true" />
      <Item Name="doSpikeKiller" Value="true" />
      <Item Name="lumi_file" Value="common/data/2017/Cert_294927-306462_13TeV_EOY2017ReReco_Collisions17_JSON_v1.root"/>
      <Item Name="NLOweightsDir" Value="UHHNtupleConverter/NLOweights"/>
      <Item Name="pileup_directory_data" Value="common/data/2017/MyDataPileupHistogram.root" />
      <Item Name="pileup_directory" Value="common/data/2017/MyMCPileupHistogram.root" />
      <Item Name="AnalysisModule" Value="PreSelModule"/>
    </UserConfig>
  </Cycle>

  <Cycle Name="uhh2::AnalysisModuleRunner" OutputDirectory="&OUTdir;/PF_flavours/" PostFix="" TargetLumi="41860">
    &SAMPLES;
    <UserConfig>
      <Item Name="GridFile" Value="JetMass/Histograms/grid_PF_flavours.root" />
      <Item Name="channel" Value="W"/>
      <Item Name="PrimaryVertexCollection" Value="offlineSlimmedPrimaryVertices"/>
      <Item Name="GenParticleCollection"   Value="GenParticles"/>
      <Item Name="ElectronCollection"      Value="slimmedElectronsUSER"/>
      <Item Name="MuonCollection"          Value="slimmedMuonsUSER"/>
      <Item Name="JetCollection"           Value="jetsAk4CHS"/>
      <Item Name="GenJetCollection"        Value="slimmedGenJets"/>
      <Item Name="TopJetCollection"        Value="jetsAk8PuppiSubstructure_SoftDropPuppi"/>
      <Item Name="GenTopJetCollection"     Value="genjetsAk8SubstructureSoftDrop" />
      <Item Name="PFParticleCollection"    Value="PFParticles"/>
      <Item Name="METName"                 Value="slimmedMETs"/>
      <Item Name="use_sframe_weight" Value="false"/>
      <Item Name="dometfilters" Value="true" />
      <Item Name="dopvfilter" Value="true" />
      <Item Name="doSpikeKiller" Value="true" />
      <Item Name="lumi_file" Value="common/data/2017/Cert_294927-306462_13TeV_EOY2017ReReco_Collisions17_JSON_v1.root"/>
      <Item Name="NLOweightsDir" Value="UHHNtupleConverter/NLOweights"/>
      <Item Name="pileup_directory_data" Value="common/data/2017/MyDataPileupHistogram.root" />
      <Item Name="pileup_directory" Value="common/data/2017/MyMCPileupHistogram.root" />
      <Item Name="AnalysisModule" Value="PreSelModule"/>
    </UserConfig>
  </Cycle>


  <Cycle Name="uhh2::AnalysisModuleRunner" OutputDirectory="&OUTdir;/2ptbins/" PostFix="" TargetLumi="41860">
    &SAMPLES;
    <UserConfig>
      <Item Name="GridFile" Value="JetMass/Histograms/grid_2ptbins.root" />
      <Item Name="channel" Value="W"/>
      <Item Name="PrimaryVertexCollection" Value="offlineSlimmedPrimaryVertices"/>
      <Item Name="GenParticleCollection"   Value="GenParticles"/>
      <Item Name="ElectronCollection"      Value="slimmedElectronsUSER"/>
      <Item Name="MuonCollection"          Value="slimmedMuonsUSER"/>
      <Item Name="JetCollection"           Value="jetsAk4CHS"/>
      <Item Name="GenJetCollection"        Value="slimmedGenJets"/>
      <Item Name="TopJetCollection"        Value="jetsAk8PuppiSubstructure_SoftDropPuppi"/>
      <Item Name="GenTopJetCollection"     Value="genjetsAk8SubstructureSoftDrop" />
      <Item Name="PFParticleCollection"    Value="PFParticles"/>
      <Item Name="METName"                 Value="slimmedMETs"/>
      <Item Name="use_sframe_weight" Value="false"/>
      <Item Name="dometfilters" Value="true" />
      <Item Name="dopvfilter" Value="true" />
      <Item Name="doSpikeKiller" Value="true" />
      <Item Name="lumi_file" Value="common/data/2017/Cert_294927-306462_13TeV_EOY2017ReReco_Collisions17_JSON_v1.root"/>
      <Item Name="NLOweightsDir" Value="UHHNtupleConverter/NLOweights"/>
      <Item Name="pileup_directory_data" Value="common/data/2017/MyDataPileupHistogram.root" />
      <Item Name="pileup_directory" Value="common/data/2017/MyMCPileupHistogram.root" />
      <Item Name="AnalysisModule" Value="PreSelModule"/>
    </UserConfig>
  </Cycle>


  <Cycle Name="uhh2::AnalysisModuleRunner" OutputDirectory="&OUTdir;/2etabins/" PostFix="" TargetLumi="41860">
    &SAMPLES;
    <UserConfig>
      <Item Name="GridFile" Value="JetMass/Histograms/grid_2etabins.root" />
      <Item Name="channel" Value="W"/>
      <Item Name="PrimaryVertexCollection" Value="offlineSlimmedPrimaryVertices"/>
      <Item Name="GenParticleCollection"   Value="GenParticles"/>
      <Item Name="ElectronCollection"      Value="slimmedElectronsUSER"/>
      <Item Name="MuonCollection"          Value="slimmedMuonsUSER"/>
      <Item Name="JetCollection"           Value="jetsAk4CHS"/>
      <Item Name="GenJetCollection"        Value="slimmedGenJets"/>
      <Item Name="TopJetCollection"        Value="jetsAk8PuppiSubstructure_SoftDropPuppi"/>
      <Item Name="GenTopJetCollection"     Value="genjetsAk8SubstructureSoftDrop" />
      <Item Name="PFParticleCollection"    Value="PFParticles"/>
      <Item Name="METName"                 Value="slimmedMETs"/>
      <Item Name="use_sframe_weight" Value="false"/>
      <Item Name="dometfilters" Value="true" />
      <Item Name="dopvfilter" Value="true" />
      <Item Name="doSpikeKiller" Value="true" />
      <Item Name="lumi_file" Value="common/data/2017/Cert_294927-306462_13TeV_EOY2017ReReco_Collisions17_JSON_v1.root"/>
      <Item Name="NLOweightsDir" Value="UHHNtupleConverter/NLOweights"/>
      <Item Name="pileup_directory_data" Value="common/data/2017/MyDataPileupHistogram.root" />
      <Item Name="pileup_directory" Value="common/data/2017/MyMCPileupHistogram.root" />
      <Item Name="AnalysisModule" Value="PreSelModule"/>
    </UserConfig>
  </Cycle>


  <Cycle Name="uhh2::AnalysisModuleRunner" OutputDirectory="&OUTdir;/PF_flavours_2ptbins/" PostFix="" TargetLumi="41860">
    &SAMPLES;
    <UserConfig>
      <Item Name="GridFile" Value="JetMass/Histograms/grid_PF_flavours_2ptbins.root" />
      <Item Name="channel" Value="W"/>
      <Item Name="PrimaryVertexCollection" Value="offlineSlimmedPrimaryVertices"/>
      <Item Name="GenParticleCollection"   Value="GenParticles"/>
      <Item Name="ElectronCollection"      Value="slimmedElectronsUSER"/>
      <Item Name="MuonCollection"          Value="slimmedMuonsUSER"/>
      <Item Name="JetCollection"           Value="jetsAk4CHS"/>
      <Item Name="GenJetCollection"        Value="slimmedGenJets"/>
      <Item Name="TopJetCollection"        Value="jetsAk8PuppiSubstructure_SoftDropPuppi"/>
      <Item Name="GenTopJetCollection"     Value="genjetsAk8SubstructureSoftDrop" />
      <Item Name="PFParticleCollection"    Value="PFParticles"/>
      <Item Name="METName"                 Value="slimmedMETs"/>
      <Item Name="use_sframe_weight" Value="false"/>
      <Item Name="dometfilters" Value="true" />
      <Item Name="dopvfilter" Value="true" />
      <Item Name="doSpikeKiller" Value="true" />
      <Item Name="lumi_file" Value="common/data/2017/Cert_294927-306462_13TeV_EOY2017ReReco_Collisions17_JSON_v1.root"/>
      <Item Name="NLOweightsDir" Value="UHHNtupleConverter/NLOweights"/>
      <Item Name="pileup_directory_data" Value="common/data/2017/MyDataPileupHistogram.root" />
      <Item Name="pileup_directory" Value="common/data/2017/MyMCPileupHistogram.root" />
      <Item Name="AnalysisModule" Value="PreSelModule"/>
    </UserConfig>
  </Cycle>

  <Cycle Name="uhh2::AnalysisModuleRunner" OutputDirectory="&OUTdir;/PF_flavours_2etabins/" PostFix="" TargetLumi="41860">
    &SAMPLES;
    <UserConfig>
      <Item Name="GridFile" Value="JetMass/Histograms/grid_PF_flavours_2etabins.root" />
      <Item Name="channel" Value="W"/>
      <Item Name="PrimaryVertexCollection" Value="offlineSlimmedPrimaryVertices"/>
      <Item Name="GenParticleCollection"   Value="GenParticles"/>
      <Item Name="ElectronCollection"      Value="slimmedElectronsUSER"/>
      <Item Name="MuonCollection"          Value="slimmedMuonsUSER"/>
      <Item Name="JetCollection"           Value="jetsAk4CHS"/>
      <Item Name="GenJetCollection"        Value="slimmedGenJets"/>
      <Item Name="TopJetCollection"        Value="jetsAk8PuppiSubstructure_SoftDropPuppi"/>
      <Item Name="GenTopJetCollection"     Value="genjetsAk8SubstructureSoftDrop" />
      <Item Name="PFParticleCollection"    Value="PFParticles"/>
      <Item Name="METName"                 Value="slimmedMETs"/>
